version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: vachetta-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: vachetta-ecom
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - vachetta-network

  # Optional: MongoDB Express for database administration
  mongo-express:
    image: mongo-express:latest
    container_name: vachetta-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - vachetta-network

volumes:
  mongodb_data:
    driver: local

networks:
  vachetta-network:
    driver: bridge
